## File generated by the BNF Converter (bnfc 2.9.5).

# Makefile for building the parser and test program.

GHC        = ghc
GHC_OPTS   = -package containers -package mtl
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : MyLatte/Test Main

# Rules for building the parser.

MyLatte/Abs.hs MyLatte/Lex.x MyLatte/Par.y MyLatte/Print.hs MyLatte/Test.hs Main.hs Types.hs Interpreter.hs: myLatte.cf
	bnfc --haskell -d --functor myLatte.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

MyLatte/Test : MyLatte/Abs.hs MyLatte/Lex.hs MyLatte/Par.hs MyLatte/Print.hs MyLatte/Test.hs
	${GHC} ${GHC_OPTS} $@

Main : MyLatte/Abs.hs MyLatte/Lex.hs MyLatte/Par.hs MyLatte/Print.hs Interpreter.hs Types.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f MyLatte/*.hi MyLatte/*.o MyLatte/*.log MyLatte/*.aux MyLatte/*.dvi *.hi *.o *.log *.aux *.dvi

distclean : clean
	-rm -f MyLatte/Abs.hs MyLatte/Abs.hs.bak MyLatte/ComposOp.hs MyLatte/ComposOp.hs.bak MyLatte/Doc.txt MyLatte/Doc.txt.bak MyLatte/ErrM.hs MyLatte/ErrM.hs.bak MyLatte/Layout.hs MyLatte/Layout.hs.bak MyLatte/Lex.x MyLatte/Lex.x.bak MyLatte/Par.y MyLatte/Par.y.bak MyLatte/Print.hs MyLatte/Print.hs.bak MyLatte/Skel.hs MyLatte/Skel.hs.bak MyLatte/Test.hs MyLatte/Test.hs.bak MyLatte/XML.hs MyLatte/XML.hs.bak MyLatte/AST.agda MyLatte/AST.agda.bak MyLatte/Parser.agda MyLatte/Parser.agda.bak MyLatte/IOLib.agda MyLatte/IOLib.agda.bak MyLatte/Main.agda MyLatte/Main.agda.bak MyLatte/myLatte.dtd MyLatte/myLatte.dtd.bak MyLatte/Test MyLatte/Lex.hs MyLatte/Par.hs MyLatte/Par.info MyLatte/ParData.hs
	-rmdir -p MyLatte/
	-rm -f Main

# EOF
