-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for MyLatte.

module MyLatte.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified MyLatte.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print MyLatte.Abs.Ident where
  prt _ (MyLatte.Abs.Ident i) = doc $ showString i
instance Print (MyLatte.Abs.Program' a) where
  prt i = \case
    MyLatte.Abs.Program _ topdefs -> prPrec i 0 (concatD [prt 0 topdefs])

instance Print (MyLatte.Abs.TopDef' a) where
  prt i = \case
    MyLatte.Abs.FnDef _ type_ id_ args block -> prPrec i 0 (concatD [prt 0 type_, prt 0 id_, doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])

instance Print [MyLatte.Abs.TopDef' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (MyLatte.Abs.Arg' a) where
  prt i = \case
    MyLatte.Abs.Argref _ passmode referencabletype id_ -> prPrec i 0 (concatD [prt 0 passmode, prt 0 referencabletype, prt 0 id_])
    MyLatte.Abs.Argfun _ funtype id_ -> prPrec i 0 (concatD [prt 0 funtype, prt 0 id_])

instance Print (MyLatte.Abs.PassMode' a) where
  prt i = \case
    MyLatte.Abs.PassValue _ -> prPrec i 0 (concatD [doc (showString "val")])
    MyLatte.Abs.PassRef _ -> prPrec i 0 (concatD [doc (showString "ref")])

instance Print [MyLatte.Abs.Arg' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (MyLatte.Abs.Block' a) where
  prt i = \case
    MyLatte.Abs.Block _ stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [MyLatte.Abs.Stmt' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (MyLatte.Abs.Stmt' a) where
  prt i = \case
    MyLatte.Abs.Empty _ -> prPrec i 0 (concatD [doc (showString ";")])
    MyLatte.Abs.BStmt _ block -> prPrec i 0 (concatD [prt 0 block])
    MyLatte.Abs.Decl _ type_ items -> prPrec i 0 (concatD [prt 0 type_, prt 0 items, doc (showString ";")])
    MyLatte.Abs.Ass _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    MyLatte.Abs.Incr _ id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "++"), doc (showString ";")])
    MyLatte.Abs.Decr _ id_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "--"), doc (showString ";")])
    MyLatte.Abs.Ret _ expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    MyLatte.Abs.Cond _ expr stmt -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    MyLatte.Abs.CondElse _ expr stmt1 stmt2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt1, doc (showString "else"), prt 0 stmt2])
    MyLatte.Abs.While _ expr stmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    MyLatte.Abs.SExp _ expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])

instance Print (MyLatte.Abs.Item' a) where
  prt i = \case
    MyLatte.Abs.NoInit _ id_ -> prPrec i 0 (concatD [prt 0 id_])
    MyLatte.Abs.Init _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr])

instance Print [MyLatte.Abs.Item' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (MyLatte.Abs.Type' a) where
  prt i = \case
    MyLatte.Abs.Referencable _ referencabletype -> prPrec i 0 (concatD [prt 0 referencabletype])
    MyLatte.Abs.NonReferencable _ funtype -> prPrec i 0 (concatD [prt 0 funtype])
    MyLatte.Abs.Fun _ type_ types -> prPrec i 0 (concatD [prt 0 type_, doc (showString "("), prt 0 types, doc (showString ")")])

instance Print (MyLatte.Abs.ReferencableType' a) where
  prt i = \case
    MyLatte.Abs.Int _ -> prPrec i 0 (concatD [doc (showString "int")])
    MyLatte.Abs.Str _ -> prPrec i 0 (concatD [doc (showString "string")])
    MyLatte.Abs.Bool _ -> prPrec i 0 (concatD [doc (showString "boolean")])

instance Print (MyLatte.Abs.FunType' a) where
  prt i = \case
    MyLatte.Abs.FunctionType _ type_ args -> prPrec i 0 (concatD [doc (showString "function"), prt 0 type_, doc (showString "("), prt 0 args, doc (showString ")")])

instance Print [MyLatte.Abs.Type' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (MyLatte.Abs.Expr' a) where
  prt i = \case
    MyLatte.Abs.EVar _ id_ -> prPrec i 6 (concatD [prt 0 id_])
    MyLatte.Abs.ELitInt _ n -> prPrec i 6 (concatD [prt 0 n])
    MyLatte.Abs.ELitTrue _ -> prPrec i 6 (concatD [doc (showString "true")])
    MyLatte.Abs.ELitFalse _ -> prPrec i 6 (concatD [doc (showString "false")])
    MyLatte.Abs.EApp _ id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    MyLatte.Abs.LApp _ args block exprs -> prPrec i 6 (concatD [doc (showString "lambda"), doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block, doc (showString "("), prt 0 exprs, doc (showString ")")])
    MyLatte.Abs.EString _ str -> prPrec i 6 (concatD [printString str])
    MyLatte.Abs.Neg _ expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    MyLatte.Abs.Not _ expr -> prPrec i 5 (concatD [doc (showString "!"), prt 6 expr])
    MyLatte.Abs.EMul _ expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    MyLatte.Abs.EAdd _ expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    MyLatte.Abs.ERel _ expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    MyLatte.Abs.EAnd _ expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    MyLatte.Abs.EOr _ expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
    MyLatte.Abs.Lexpr _ args block -> prPrec i 0 (concatD [doc (showString "lambda"), doc (showString "("), prt 0 args, doc (showString ")"), prt 0 block])

instance Print [MyLatte.Abs.Expr' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (MyLatte.Abs.AddOp' a) where
  prt i = \case
    MyLatte.Abs.Plus _ -> prPrec i 0 (concatD [doc (showString "+")])
    MyLatte.Abs.Minus _ -> prPrec i 0 (concatD [doc (showString "-")])

instance Print (MyLatte.Abs.MulOp' a) where
  prt i = \case
    MyLatte.Abs.Times _ -> prPrec i 0 (concatD [doc (showString "*")])
    MyLatte.Abs.Div _ -> prPrec i 0 (concatD [doc (showString "/")])
    MyLatte.Abs.Mod _ -> prPrec i 0 (concatD [doc (showString "%")])

instance Print (MyLatte.Abs.RelOp' a) where
  prt i = \case
    MyLatte.Abs.LTH _ -> prPrec i 0 (concatD [doc (showString "<")])
    MyLatte.Abs.LE _ -> prPrec i 0 (concatD [doc (showString "<=")])
    MyLatte.Abs.GTH _ -> prPrec i 0 (concatD [doc (showString ">")])
    MyLatte.Abs.GE _ -> prPrec i 0 (concatD [doc (showString ">=")])
    MyLatte.Abs.EQU _ -> prPrec i 0 (concatD [doc (showString "==")])
    MyLatte.Abs.NE _ -> prPrec i 0 (concatD [doc (showString "!=")])
