-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module MyLatte.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified MyLatte.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: MyLatte.Abs.Ident -> Result
transIdent x = case x of
  MyLatte.Abs.Ident string -> failure x

transProgram :: Show a => MyLatte.Abs.Program' a -> Result
transProgram x = case x of
  MyLatte.Abs.Program _ topdefs -> failure x

transTopDef :: Show a => MyLatte.Abs.TopDef' a -> Result
transTopDef x = case x of
  MyLatte.Abs.FnDef _ type_ ident args block -> failure x

transArg :: Show a => MyLatte.Abs.Arg' a -> Result
transArg x = case x of
  MyLatte.Abs.Argref _ passmode referencabletype ident -> failure x
  MyLatte.Abs.Argfun _ funtype ident -> failure x

transPassMode :: Show a => MyLatte.Abs.PassMode' a -> Result
transPassMode x = case x of
  MyLatte.Abs.PassValue _ -> failure x
  MyLatte.Abs.PassRef _ -> failure x

transBlock :: Show a => MyLatte.Abs.Block' a -> Result
transBlock x = case x of
  MyLatte.Abs.Block _ stmts -> failure x

transStmt :: Show a => MyLatte.Abs.Stmt' a -> Result
transStmt x = case x of
  MyLatte.Abs.Empty _ -> failure x
  MyLatte.Abs.BStmt _ block -> failure x
  MyLatte.Abs.Decl _ type_ items -> failure x
  MyLatte.Abs.Ass _ ident expr -> failure x
  MyLatte.Abs.Incr _ ident -> failure x
  MyLatte.Abs.Decr _ ident -> failure x
  MyLatte.Abs.Ret _ expr -> failure x
  MyLatte.Abs.Cond _ expr stmt -> failure x
  MyLatte.Abs.CondElse _ expr stmt1 stmt2 -> failure x
  MyLatte.Abs.While _ expr stmt -> failure x
  MyLatte.Abs.SExp _ expr -> failure x

transItem :: Show a => MyLatte.Abs.Item' a -> Result
transItem x = case x of
  MyLatte.Abs.NoInit _ ident -> failure x
  MyLatte.Abs.Init _ ident expr -> failure x

transType :: Show a => MyLatte.Abs.Type' a -> Result
transType x = case x of
  MyLatte.Abs.Referencable _ referencabletype -> failure x
  MyLatte.Abs.NonReferencable _ funtype -> failure x
  MyLatte.Abs.Fun _ type_ types -> failure x

transReferencableType :: Show a => MyLatte.Abs.ReferencableType' a -> Result
transReferencableType x = case x of
  MyLatte.Abs.Int _ -> failure x
  MyLatte.Abs.Str _ -> failure x
  MyLatte.Abs.Bool _ -> failure x

transFunType :: Show a => MyLatte.Abs.FunType' a -> Result
transFunType x = case x of
  MyLatte.Abs.FunctionType _ type_ args -> failure x

transExpr :: Show a => MyLatte.Abs.Expr' a -> Result
transExpr x = case x of
  MyLatte.Abs.EVar _ ident -> failure x
  MyLatte.Abs.ELitInt _ integer -> failure x
  MyLatte.Abs.ELitTrue _ -> failure x
  MyLatte.Abs.ELitFalse _ -> failure x
  MyLatte.Abs.EApp _ ident exprs -> failure x
  MyLatte.Abs.LApp _ args block exprs -> failure x
  MyLatte.Abs.EString _ string -> failure x
  MyLatte.Abs.Neg _ expr -> failure x
  MyLatte.Abs.Not _ expr -> failure x
  MyLatte.Abs.EMul _ expr1 mulop expr2 -> failure x
  MyLatte.Abs.EAdd _ expr1 addop expr2 -> failure x
  MyLatte.Abs.ERel _ expr1 relop expr2 -> failure x
  MyLatte.Abs.EAnd _ expr1 expr2 -> failure x
  MyLatte.Abs.EOr _ expr1 expr2 -> failure x
  MyLatte.Abs.Lexpr _ args block -> failure x

transAddOp :: Show a => MyLatte.Abs.AddOp' a -> Result
transAddOp x = case x of
  MyLatte.Abs.Plus _ -> failure x
  MyLatte.Abs.Minus _ -> failure x

transMulOp :: Show a => MyLatte.Abs.MulOp' a -> Result
transMulOp x = case x of
  MyLatte.Abs.Times _ -> failure x
  MyLatte.Abs.Div _ -> failure x
  MyLatte.Abs.Mod _ -> failure x

transRelOp :: Show a => MyLatte.Abs.RelOp' a -> Result
transRelOp x = case x of
  MyLatte.Abs.LTH _ -> failure x
  MyLatte.Abs.LE _ -> failure x
  MyLatte.Abs.GTH _ -> failure x
  MyLatte.Abs.GE _ -> failure x
  MyLatte.Abs.EQU _ -> failure x
  MyLatte.Abs.NE _ -> failure x
